import type { Metadata } from "next";

import { Tajawal } from "next/font/google";

import "./globals.css";

import Navbar from "@/components/layout/navbar";
import MobileNav from "@/components/layout/mobileNav";
import Accordion from "@/components/accordion/accordion";

import { getCats } from "@/lib/contentful/data";

import Footer from "@/components/footer/footer";

const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hideFooter = true;

  const cats = await getCats();

  return (
    <html lang="ar" dir="rtl">
      <body className={`min-h-screen ${tajawal.className}`}>
        <Navbar />
        <main>{children}</main>
        {hideFooter && (
          <>
            <section className="lg:hidden">
              <div className="bg-red-100">
                <Accordion cats={cats} />
              </div>
            </section>
            <Footer />
          </>
        )}
        <MobileNav />
      </body>
    </html>
  );
}
