import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import MobileNav from "@/components/mobileNav";

// Import the Arabic font with fallback fonts
const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "الشروق",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`min-h-screen ${tajawal.className}`}>
        <Navbar />
        <main>{children}</main>
        <MobileNav />
      </body>
    </html>
  );
}
